### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by RitaHC** [sei-ec-remote/project-1-issues#146]
### What's the problem you're trying to solve?

---Unable to flip my animation screen

### Post any code you think might be relevant (one fenced block per file)
```
---this.timeSinceFlap += deltaTime
        if(this.timeSinceFlap>this.flapInterval){
            if(this.frame > this.maxFrame) {
                this.frame = 0
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

No Error Displayed

### What is your best guess as to the source of the problem?

the sprite frame is not chaning

### What things have you already tried to solve the problem?

---Trained calculating deltaTime 
---Online resources

### Paste a link to your repository here

https://github.com/RitaHC/Raven-Hunt

**Comment by timmshinbone** [comment]
Hey Rita, we need a little more context here. Could you go into more detail about what you mean by `flip animation screen` and share a little more code so we can see how your animation screen is running?

**Comment by asands94** [comment]
@timmshinbone After talking with Rita a little bit ago, she was having an issue with her birds wings not flapping. She has 2 classes of birds, ravens and beige birds. The ravens wings flap, but the beige birds wings do not. We got the beige birds wings flapping, now the issue is just making it so the wings on the beige bird are not flapping extremely fast
