### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by tayanaHL** [sei-ec-remote/project-1-issues#153]
### What's the problem you're trying to solve?
Trying to get my button element to play sounds.

### Post any code you think might be relevant (one fenced block per file)
```
HTML
<button class="playbtn">Play Sound</button>
    <audio autoplay id="audio1" src="sounds/pacman.mp3"></audio>
JS
const myAudio = document.createElement("audio1");
myAudio.src = "sounds/pacman.mp3";

myAudio.play();
myAudio.pause()
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message. Not sure what the proper syntax is to play audio by clicking a button.

### What is your best guess as to the source of the problem?
That I'm doing it incorrectly.

### What things have you already tried to solve the problem?

I tried using stack overflow and MDN, but I had no luck with other solutions.

**Comment by asands94** [comment]
Hey Tayana! It looks like you're creating an element called `audio1` instead of selecting an id of `audio1`. Also, make sure to add a link to your repo so we can see all your code. If you haven't yet, make sure all the other functionality of the game is working before adding in music! Audio extras are not super important for the game to be cool

**Comment by tayanaHL** [comment]
getElementByID
