### ISSUE TITLE
Issue with extending Array class

### ISSUE THREAD

**Issue by f-eiyu** [sei-ec-remote/project-1-issues#57]
### What's the problem you're trying to solve?
I'm having trouble with properly extending the Array class. I think it could just be a js syntax thing that I'm not familiar with, and I'm having a hard time finding the correct search terms for this specific issue (I spent about half an hour trying to look this problem up yesterday).

### Post any code you think might be relevant (one fenced block per file)
```
class MyTestClass extends Array {
    constructor(arr) {
        super(...arr);
        this.myTestProp = 3.14159;
    }
    
    squareContents() {
        return this.map(n => n** 2);
    }
}
  
const test = new MyTestClass([1, 2, 3, 4]);
console.log(test.myTestProp); // works fine
console.log(test.squareContents()); // throws exception
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
Uncaught TypeError: Found non-callable @@iterator
    at new MyTestClass (game.js:5:9)
    at MyTestClass.map (<anonymous>)
    at MyTestClass.squareContents (game.js:10:21)
    at game.js:17:18
```

### What is your best guess as to the source of the problem?
Clearly something is going wrong when I'm trying to use my extended Array, but I'm kind of at a loss as to what it is.

### What things have you already tried to solve the problem?
For now, I'm working around the problem by just sticking the data in an array as a class property and creating wrappers to use the array methods on the data, instead of trying to use the class itself as an array. This works fine, but the fact that MDN enthusiastically tells me that Array can be extended makes me feel like there's probably some more idiomatic solution that I'm totally missing.

### Paste a link to your repository here
Not necessary for this issue.

**Comment by mattkeane-ga** [comment]
This is a bit complex. Not to get into _too_ much theory, but JavaScript is pretty weird when it comes to OOP. The short answer is that classes are not "real" in JavaScript, but were added as syntactic sugar in ES6. Rather than following classical inheritance, JavaScript follows a model called prototypal inheritance and when you try to extend built in classes, you can get some weird results like this.

My recommendation would be to follow a simpler pattern. Instead of creating a new class that extends Array, why not create a class that has an array as a property and then go from there? Or simply use a external function to get the desired results?

**Comment by f-eiyu** [comment]
Sounds good -- using the array as a property is the workaround solution I was going with anyways, so that should work just fine. This is great information to have and I'm sure I'll make more use of it once I'm more familiar with the architecture of JavaScript.

Thanks, Matt!
